#!/bin/bash

if ! [ -c /dev/tty.usb* ]; then
  echo -n 'Waiting for /dev/tty.usb* to appear..'
fi

while true; do
  while ! [ -c /dev/tty.usb* ]; do
    echo -n '.'
    sleep 0.4
  done
  device=/dev/tty.usb*
  screen $device 115200
  if ! [ -c $device ]; then
    echo -n "$device vanished; waiting for it to reappear.."
  else
    break
  fi
done
