#!/bin/bash

# Extracts and displays the last dumped screen frame in a screenlog file.

# Find the line preceding the last occurrence of [[FRAME]].
grep -B 1 '^\[\[FRAME\]\]' screenlog.0 | tail -2 | head -1 | \
    # Convert the hex digits to bytes.
    python -c 'import binascii, os, sys; os.fdopen(1, "wb").write(b"P6\n192 32\n255\n" + binascii.unhexlify(sys.stdin.read().strip()))' | \
    # Convert the PNM file to a PNG.
    pnmtopng >/tmp/frame.new 2>/dev/null && mv /tmp/frame.new /tmp/frame.png && \
    # Move focus away from Preview, which prevents Preview from opening a new window on the same image.
    open -a dock && \
    # Tell Preview to view (or reload) the image.
    open /tmp/frame.png
