#!/bin/bash

cd $(dirname "$0")
cd ..

module="$1"
module=${module%.py}
target=/Volumes/CIRCUITPY
unalias -a

if [ -z "$module" ]; then
    echo "Usage: $0 <module>"
    echo
    echo "Runs a module on the attached CircuitPython device, using"
    echo "adafruit.rgbmatrix as the graphics driver."
    exit 1
fi

if ! python -c "from $module import run"; then
    exit 1
fi

if [ ! -d "$target" ]; then
    echo "No drive found at $target.  Is a CircuitPython device connected?"
    exit 1
fi

mkdir -p $target/lib
for lib in bitmap_font datetime display_text ds3231 esp32spi matrixportal requests; do
    rm -rf $target/lib/adafruit_$lib*
    cp -r cache/lib/adafruit_$lib* $target/lib/
done

cp *.py $target

cat <<EOF >$target/code.py
import matrix_frame
frame = matrix_frame.new_display_frame(192, 32, 64)

from $module import run
run(frame)
EOF
