#!/bin/bash -e

cd $(dirname "$0")
cd ..

if [ "$1" = -q ]; then
    quick=yes
    shift
fi

module="$1"
module=${module%.py}
target=/Volumes/CIRCUITPY
unalias -a

# TODO: Deploy start.py in such a way that it runs $module, instead of
# always running the "app" module.

if [ -z "$module" ]; then
    echo "Usage: $0 [-q] <module>"
    echo
    echo "Runs a module on the attached CircuitPython device, using"
    echo "adafruit.rgbmatrix as the graphics driver.  Specify -q for"
    echo "a quick run (skip reinstalling data, libraries, and fonts)."
    exit 1
fi

echo 'Checking syntax...'
python3 <<EOF || exit 1
import os
from app import run
for name in os.listdir():
    if name.endswith('.py'):
        compile(open(name).read(), name, 'exec')
EOF

if [ ! -d "$target" ]; then
    echo "No drive found at $target.  Is a CircuitPython device connected?"
    exit 1
fi

if [ ! -d cache/lib ]; then
    echo "The cache/lib directory is missing.  Did you run tools/setup?"
    exit 1
fi

echo 'Installing program modules...'
rm -rf $target/v999
mkdir $target/v999
cp *.py $target/v999

if [ -z "$quick" ]; then
    echo 'Installing climateclock.json...'
    curl https://api.climateclock.world/v1/clock -o cache/climateclock.json
    mkdir -p $target/cache
    cp cache/climateclock.json $target/cache

    echo 'Installing fonts...'
    cp *.pcf $target
fi

echo 'Installing startup logic...'
rm -f $target/code.py
cp boot.py gpio.py main.py $target

touch $target/v999/@VALID
touch $target/v999/@ENABLED
sync
echo 'All done!'
