#!/usr/bin/env python -i

import os
import sys

# All times on the board are in UTC.
os.environ['TZ'] = 'UTC'

# Set the import paths relative to the parent of the tools/ directory.
command = sys.argv[0]
os.chdir(os.path.dirname(command))
os.chdir('..')
sys.path.append('.')
sys.path.append('simulator')

