#!/usr/bin/env python3

import os
import re
import sys

command = sys.argv[0]
os.chdir(os.path.dirname(command))
os.chdir('..')
os.environ['TZ'] = 'UTC'  # all times on the board are in UTC

sys.path.append('.')
sys.path.append('stubs')
for name in os.listdir('.'):
    if name.startswith('Adafruit_CircuitPython'):
        sys.path.append(name)

import fs
fs.root = '/tmp/cclock'
for path in os.listdir():
    if path.endswith('.mcf'):
        fs.write(path, open(path, 'rb').read())

from unix_network import UnixNetwork
network = UnixNetwork('climateclock', 'climateclock')

import prefs
prefs.init()
import sdl2
from sdl_frame import SdlFrame, SdlButton, SdlDial
frame = SdlFrame(192, 32, 20)  # 20 fps is roughly what we get on the board
up = SdlButton(frame, sdl2.SDL_SCANCODE_LSHIFT)
down = SdlButton(frame, sdl2.SDL_SCANCODE_RSHIFT)
enter = SdlButton(frame, sdl2.SDL_SCANCODE_RETURN)
brightness = SdlDial(
    frame, sdl2.SDL_SCANCODE_DOWN, sdl2.SDL_SCANCODE_UP, 0.0, 1.0, 1/8.0)
selector = SdlDial(
    frame, sdl2.SDL_SCANCODE_LEFT, sdl2.SDL_SCANCODE_RIGHT, -100000, 100000, 1)

import app
app.run(
    network,
    frame,
    {'UP': up, 'DOWN': down, 'ENTER': enter},
    {'BRIGHTNESS': brightness, 'SELECTOR': selector}
)
