#!/usr/bin/env python3

import os
import re
import sys

command = sys.argv[0]
os.chdir(os.path.dirname(command))
os.chdir('..')

sys.path.append('.')
sys.path.append('stubs')
for name in os.listdir('.'):
    if name.startswith('Adafruit_CircuitPython'):
        sys.path.append(name)

try:
    module = sys.argv[1]
    module = re.sub(r'\.py.?$', '', module)
except:
    print(f'''\
Usage: {command} <module>

Runs a module on the local machine, using SDL as the graphics driver.
<module>.py should be a Python module containing a run() function
that takes an instance of frame.Frame as its single argument.''')
    raise SystemExit()

try:
    run = __import__(module).run
except Exception as e:
    raise SystemExit(e)

import sdl2
from sdl_frame import SdlFrame, SdlButton, SdlDial

frame = SdlFrame(192, 32, 30)
up = SdlButton(frame, sdl2.SDL_SCANCODE_LSHIFT)
down = SdlButton(frame, sdl2.SDL_SCANCODE_RSHIFT)
brightness = SdlDial(
    frame, sdl2.SDL_SCANCODE_LEFTBRACKET, sdl2.SDL_SCANCODE_RIGHTBRACKET)
run(frame, {'NEXT': up, 'ENTER': down}, {'BRIGHTNESS': brightness})
