#!/usr/bin/env python3

import os
import re
import sys

command = sys.argv[0]
os.chdir(os.path.dirname(command))
os.chdir('..')

sys.path.append('.')
sys.path.append('stubs')
for name in os.listdir('.'):
    if name.startswith('Adafruit_CircuitPython'):
        sys.path.append(name)

try:
    module = sys.argv[1]
    module = re.sub(r'\.py.?$', '', module)
except:
    print(f'''\
Usage: {command} <module>

Runs a module on the local machine, using SDL as the graphics driver.
<module>.py should be a Python module containing a run() function
that takes an instance of frame.Frame as its single argument.''')
    raise SystemExit()

run = __import__(module).run

import sdl2
from sdl_frame import SdlFrame, SdlButton, SdlDial

from fs import FileSystem
from unix_network import UnixNetwork
network = UnixNetwork('climateclock', 'climateclock', debug=True)

frame = SdlFrame(192, 32, 30)
up = SdlButton(frame, sdl2.SDL_SCANCODE_LSHIFT)
down = SdlButton(frame, sdl2.SDL_SCANCODE_RSHIFT)
enter = SdlButton(frame, sdl2.SDL_SCANCODE_RETURN)
brightness = SdlDial(
    frame, sdl2.SDL_SCANCODE_DOWN, sdl2.SDL_SCANCODE_UP, 0.0, 1.0, 1/8.0)
selector = SdlDial(
    frame, sdl2.SDL_SCANCODE_LEFT, sdl2.SDL_SCANCODE_RIGHT, -100000, 100000, 1)
run(
    FileSystem(b'/tmp/cclock'),
    network,
    frame,
    {'UP': up, 'DOWN': down, 'ENTER': enter},
    {'BRIGHTNESS': brightness, 'SELECTOR': selector}
)
