#!/bin/bash

if [ $(uname) = Linux ]; then
    prefix=/dev/ttyACM
else
    prefix=/dev/tty.usb
fi
prefix=${CCLOCK_SERIAL_DEVICE_PREFIX:-$prefix}

if ! [ -c "$prefix"* ]; then
    echo -n "Waiting for $prefix* to appear.."
fi

while true; do
    while ! [ -c "$prefix"* ]; do
        echo -n '.'
        sleep 0.05
    done
    device="$prefix"*
    cat <<EOF >/tmp/screenrc
logfile flush 0
defscrollback 10000
EOF
    cat <<EOF >>screenlog.0


==== Starting screen: $(date) ====
EOF
    screen -c /tmp/screenrc -L $device 115200
    if ! [ -c $device ]; then
        echo -n "$device vanished; waiting for it to reappear.."
    else
        break
    fi
done
