#!/usr/bin/env python3

import os
import sys

# All times on the board are in UTC.
os.environ['TZ'] = 'UTC'

# sim.py installs the simulator monkey-patches.
os.environ['CCLOCK_SIMULATOR_PATH'] = os.getcwd() + '/simulator'
with open('/tmp/cclock/sim.py', 'w') as opt:
    with open('simulator/sim.py') as ipt:
        opt.write(ipt.read())

# Off we go!
os.chdir('/tmp/cclock')
sys.path = ['.'] + sys.path
import main
